serial_no: 32703551
cam_name: "cameraRight"
yaml_url: "package://autorally_core/calibrations/cameraRight.yaml"
exposure_time: 6000
rect_left: 0
rect_top: 0
rect_height: 1024
rect_width: 1280
image_data_format: "XI_RGB24"
trigger_source: 1